// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTl6tBQQJYg9HLV95o16dqK9GmvQ7myAU',
    appId: '1:69494869682:web:8136fe0695c3c4b28d83ab',
    messagingSenderId: '69494869682',
    projectId: 'esp32-e82a7',
    authDomain: 'esp32-e82a7.firebaseapp.com',
    storageBucket: 'esp32-e82a7.firebasestorage.app',
    measurementId: 'G-DJGHZBLP43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbfSWs4B7CB9PvsbvqQD7WJFWv5m9CSc',
    appId: '1:69494869682:android:6a14e14f8269d1728d83ab',
    messagingSenderId: '69494869682',
    projectId: 'esp32-e82a7',
    storageBucket: 'esp32-e82a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzuRT4EHnTCt8161Nl1ejdXqmIHetXxk',
    appId: '1:69494869682:ios:73aa1fee783c25698d83ab',
    messagingSenderId: '69494869682',
    projectId: 'esp32-e82a7',
    storageBucket: 'esp32-e82a7.firebasestorage.app',
    iosBundleId: 'fr.umontpellier.esp32App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATzuRT4EHnTCt8161Nl1ejdXqmIHetXxk',
    appId: '1:69494869682:ios:73aa1fee783c25698d83ab',
    messagingSenderId: '69494869682',
    projectId: 'esp32-e82a7',
    storageBucket: 'esp32-e82a7.firebasestorage.app',
    iosBundleId: 'fr.umontpellier.esp32App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTl6tBQQJYg9HLV95o16dqK9GmvQ7myAU',
    appId: '1:69494869682:web:593ebbaeef3b5a928d83ab',
    messagingSenderId: '69494869682',
    projectId: 'esp32-e82a7',
    authDomain: 'esp32-e82a7.firebaseapp.com',
    storageBucket: 'esp32-e82a7.firebasestorage.app',
    measurementId: 'G-PTRGGKW4ZW',
  );
}
